### ISSUE TITLE
MacOs fix

### ISSUE THREAD

**Issue by fellnerse** [scito/extract_otp_secrets#231] opened 2024-05-29 09:56 UTC
Hey @scito !
Awesome tool, thanks for providing it! I debuged your script for mac and found the problem for only poping up one frame:

this [check](https://github.com/scito/extract_otp_secrets/blob/7f314cedd8937540615b34356f7d425a0f44842e/src/extract_otp_secrets.py#L505) seems to be always true. After disabling it, I was able to run your application successfully. Obviously closing doesn't work anymore, not sure if there is another way for checking it.

**Comment by scito** [comment] 2024-05-29 19:42
Hm, interesting issue. Unfortunatley, I don't have MacOS anymore. Thus, I cannot reproduce and fix it at the moment.

In requirements.txt, I limited opencv to 4.7.0. Can you change your requirements.txt `opencv-contrib-python>4.7.0; sys_platform == 'darwin'` and try again?
Maybe, it works now with new opencv versions.

How do you get this extract_otp_secrets script? By GitHub, pip, ...?

**Comment by scito** [comment] 2024-05-29 20:28
I changed the opencv-contrib-python config for macos. It passes the tests. Can you try with the master?

**Comment by fellnerse** [comment] 2024-05-30 09:29
> How do you get this extract_otp_secrets script? By GitHub, pip, ...?
I pulled the latest commit from github.

>I changed the opencv-contrib-python config for macos. It passes the tests. Can you try with the master?
Yes! it fixed it! thanks! the closing also works with ESC. But the red close button of the window is disabled.

**Comment by scito** [comment] 2024-06-01 12:20
OK, good!
I think I cannot do anything about the red close button. Thus, I'll close this issue.

**Closed by scito** 2024-06-01 12:20 UTC
